# Form implementation generated from reading ui file 'AddFile.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import QDialog, QHBoxLayout, QLineEdit, QPushButton, QFileDialog
from PyQt6 import QtWidgets

class CustomDialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 333)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.widget.setFont(font)
        self.widget.setStatusTip("")
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.VideoNameLabel = QtWidgets.QLabel(parent=self.widget)
        palette = QtGui.QPalette()
        self.VideoNameLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.VideoNameLabel.setFont(font)
        self.VideoNameLabel.setObjectName("VideoNameLabel")
        self.gridLayout.addWidget(self.VideoNameLabel, 0, 0, 1, 1)
        self.VideoPathLabel = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.VideoPathLabel.setFont(font)
        self.VideoPathLabel.setObjectName("VideoPathLabel")
        self.gridLayout.addWidget(self.VideoPathLabel, 2, 0, 1, 1)
        self.OpenButton = QtWidgets.QPushButton(parent=self.widget)
        self.OpenButton.setObjectName("OpenButton")
        self.gridLayout.addWidget(self.OpenButton, 6, 0, 1, 1)
        self.SaveButton = QtWidgets.QPushButton(parent=self.widget)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 6, 1, 1, 1)
        self.PlayFileButton = QtWidgets.QPushButton(parent=self.widget)
        self.PlayFileButton.setObjectName("PlayFileButton")
        self.gridLayout.addWidget(self.PlayFileButton, 6, 2, 1, 1)
        self.EncryptButton = QtWidgets.QPushButton(parent=self.widget)
        self.EncryptButton.setObjectName("EncryptButton")
        self.gridLayout.addWidget(self.EncryptButton, 6, 3, 1, 1)
        self.DecryptButton = QtWidgets.QPushButton(parent=self.widget)
        self.DecryptButton.setObjectName("DecryptButton")
        self.gridLayout.addWidget(self.DecryptButton, 6, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 5)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 0, 1, 5)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 0, 1, 5)
        self.EncryptedPath = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.EncryptedPath.setFont(font)
        self.EncryptedPath.setObjectName("EncryptedPath")
        self.gridLayout.addWidget(self.EncryptedPath, 4, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget)
        self.OpenButton.clicked.connect(self.open_file_dialog)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.VideoNameLabel.setText(_translate("Dialog", "Video name"))
        self.VideoPathLabel.setText(_translate("Dialog", "Video path"))
        self.OpenButton.setText(_translate("Dialog", "Open"))
        self.SaveButton.setText(_translate("Dialog", "Save to DB"))
        self.PlayFileButton.setText(_translate("Dialog", "Play"))
        self.EncryptButton.setText(_translate("Dialog", "Encrypt"))
        self.DecryptButton.setText(_translate("Dialog", "Decrypt"))
        self.EncryptedPath.setText(_translate("Dialog", "Encrypted file path"))
    def open_file_dialog(self):
        file_dialog = QFileDialog.getOpenFileName(self, "Open File", "", "All Files (*.*)")
        if file_dialog[0]:
            self.file_path_line.setText(file_dialog[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = CustomDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
